<?php

use Illuminate\Database\Seeder;

class IngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ingredients')->insert([
            ['id' => 1, 'name' => 'Спанаќ', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 2, 'name' => 'Авокадо', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 3, 'name' => 'Краставица', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 4, 'name' => 'Сок од лимон', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 5, 'name' => 'Морска сол', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 6, 'name' => 'Бадемово млеко', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 7, 'name' => 'Банана', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 8, 'name' => 'Свежи боровинки', 'type' => '',
                'description'=>'Во однос на другите овошја боровинките содржат најмногу антиоксиданси кои позитивно влијаат врз вашето здравје. Тие помагаат во борбата против слободните радикали кои може да и наштетат на структурата на клетките и се поврзани со стареењето и подобрувањето на меморијата.',
                'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 9, 'name' => 'Замрзнати боровинки', 'type' => '',
                'description'=>'Во однос на другите овошја боровинките содржат најмногу антиоксиданси кои позитивно влијаат врз вашето здравје. Тие помагаат во борбата против слободните радикали кои може да и наштетат на структурата на клетките и се поврзани со стареењето и подобрувањето на меморијата.',
                'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 10, 'name' => 'Кисело млеко', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 11, 'name' => 'Сок од портокал', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 12, 'name' => 'Млеко', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 13, 'name' => 'Овесни слегулки', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 14, 'name' => 'Ореви', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 15, 'name' => 'Боровинки', 'type' => '',
                'description'=>'Во однос на другите овошја боровинките содржат најмногу антиоксиданси кои позитивно влијаат врз вашето здравје. Тие помагаат во борбата против слободните радикали кои може да и наштетат на структурата на клетките и се поврзани со стареењето и подобрувањето на меморијата.',
                'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 16, 'name' => 'Кељ', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 17, 'name' => 'Киви', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 18, 'name' => 'Грозје', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 19, 'name' => 'Целер', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 20, 'name' => 'Јаболко', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 21, 'name' => 'Вода', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 22, 'name' => 'Морков', 'type' => '',
                'description'=>'Морковите се богати со витамин А, го подобруваат видот, имунитетот и репродуктивниот систем. Со овој крцкав зеленчук со портокалова боја вие ќе внесете 204% од дневниот препорачан внес на витамин А, како и витамин Ц, Б3, Б6, Е и Х. Тие се исто така одлични за кожата и содржат многу малку калории.',
                'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 23, 'name' => 'Ананас', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 24, 'name' => 'Манго', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 25, 'name' => 'Кокосова вода', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 26, 'name' => 'Зрела банана', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 27, 'name' => 'Чиа семе', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 28, 'name' => 'Урма', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 29, 'name' => 'Бадеми', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 30, 'name' => 'Исечкани јаболка', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 31, 'name' => 'Цимет', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 32, 'name' => 'Јајца', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 33, 'name' => 'Путер', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 34, 'name' => 'Брашно', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 35, 'name' => 'Шеќер', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 36, 'name' => 'Цвет од брокула', 'type' => '',
                'description'=>'Истажувањата покажуваат дека брокулата помага при произведување на одредени ензими кои ги штитат крвните садови.',
                'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 37, 'name' => 'Замрзнато манго', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 38, 'name' => 'Семки од коноп', 'type' => '',
                'description'=>'Семките од коноп изобилуваат со омега 3 масни киселини и протеини кои го штитат срцето.',
                'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 39, 'name' => 'Фета сирење', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 40, 'name' => 'Сол', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 41, 'name' => 'Бибер', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 42, 'name' => 'Круша', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 43, 'name' => 'Путер од бадеми', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 44, 'name' => 'Екстракт од ванила', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 45, 'name' => 'Тофу', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 46, 'name' => 'Повеќенаменско брашно', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 47, 'name' => 'Какао', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 48, 'name' => 'Сода бикарбона', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 49, 'name' => 'Јагоди', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 50, 'name' => 'Замрзнати јагоди', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 51, 'name' => 'Малини', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 52, 'name' => 'Замрзнати малини', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 53, 'name' => 'Гоџи бобинки', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 54, 'name' => 'Кафе', 'type' => '',
                'description'=>'Докажано е дека кафето има одредени здравствени придобивки, меѓу кои и тоа дека го намалува ризикот од дијабетес тип 2 и деменција, но преголеми количини од било што може да имаат негативно влијание врз вашето здравје. Ако сте зависни од кафе, помогнете си и одвикнете се со овој хранлив шејк кој содржи мала количина на кафе и други здрави, природни и хранливи состојки.',
                'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 55, 'name' => 'Сварено кафе', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 56, 'name' => 'Изладено сварено кафе', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 57, 'name' => 'Сок од лимета', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 58, 'name' => 'Мед', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 59, 'name' => 'Кокос', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 60, 'name' => 'Путер од кикирики', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 61, 'name' => 'Нане', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 62, 'name' => 'Портокал', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 63, 'name' => 'Кајсија', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 64, 'name' => 'Кајсија без семка', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 65, 'name' => 'Какао во прав', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 66, 'name' => 'Цвекло', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 67, 'name' => 'Незасладено бадемово млеко', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 68, 'name' => 'Маслиново масло', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 69, 'name' => 'Кокосово масло', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['id' => 70, 'name' => 'Индиски орев', 'type' => '', 'description'=>'', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],

        ]);
    }
}
